# Generated by Django 6.0.1 on 2026-01-18 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to=apps.files.models.user_directory_path)),
                ("name", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="files", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
